-- AlterTable
ALTER TABLE `cutoff` ADD COLUMN `quota` VARCHAR(191) NOT NULL DEFAULT 'All India',
    ADD COLUMN `round` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `year` INTEGER NOT NULL DEFAULT 2025;
